name = "weather_risks"
target = "javascript"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 4.6.3 and < 5.0.0"
lustre_http = ">= 0.6.0 and < 1.0.0"
lustre_ui = ">= 0.4.0 and < 1.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.6.5 and < 2.0.0"
